application:
  restPkiCore:
      api-key:  "https://you_example_restpki_instance.com"
      endpoint: "ENTER_YOU_API_KEY_HERE"
  example:
    trustedOrigin: "http://localhost:4200/"
  

spring:
  application:
    name: demo

server:
  port: 5078